env: {}

prometheus:
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: "echo-server"
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: umbrella-echo-server
              action: keep
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              regex: metrics
              action: keep

grafana:
  # Default Grafana values
  enabled: true

