apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: monitoring
            environment: dev
            namespace: monitoring
            gitRef: HEAD
  template:
    metadata:
      labels:
        domain: monitoring-umbrella
      name: monitoring-{{environment}}
    spec:
      project: monitoring
      destination:
        name: '{{clusterName}}'
        namespace: '{{namespace}}'
      revisionHistoryLimit: 0
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: kube-prometheus-stack
        targetRevision: 70.4.1
        helm:
          releaseName: monitoring
          valueFiles:
          - env/{{environment}}-values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
