  apiVersion: argoproj.io/v1alpha1
  kind: ApplicationSet
  metadata:
    name: monitoring-appset
    namespace: argocd
  spec:
    generators:
    - list:
        elements:
        - clusterName: gcp-cluster
          environment: dev
          namespace: monitoring
          gitRef: HEAD
    template:
      metadata:
        labels:
          domain: monitoring-umbrella
        name: monitoring-{{environment}}
      spec:
        project: monitoring
        destination:
          name: '{{clusterName}}'
          namespace: '{{namespace}}'
        revisionHistoryLimit: 0
        source:
          helm:
            releaseName: monitoring
            valueFiles:
            - env/values-{{environment}}.yaml
          path: infra/monitoring
          repoURL: 'https://github.com/yanirw/guitarnetes2.0'
          targetRevision: '{{gitRef}}'
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
          - CreateNamespace=true