apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-test-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - clusterName: gcp-cluster
        environment: dev
        namespace: monitoring-test  # Different namespace for testing
        gitRef: your-feature-branch-name
  template:
    metadata:
      labels:
        domain: monitoring-umbrella
      name: monitoring-test-{{environment}}
    spec:
      project: monitoring
      destination:
        name: '{{clusterName}}'
        namespace: '{{namespace}}'
      revisionHistoryLimit: 0
      source:
        helm:
          releaseName: monitoring
          valueFiles:
          - env/{{environment}}-values.yaml
        path: infra/monitoring
        repoURL: 'https://github.com/yanirw/guitarnetes2.0'
        targetRevision: '{{gitRef}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true 