apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-test-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - clusterName: gcp-cluster
            environment: dev
            namespace: monitoring-test
            gitRef: feat/monitoring
  template:
    metadata:
      labels:
        domain: monitoring-umbrella
      name: monitoring-test-{{environment}}
    spec:
      project: monitoring
      destination:
        name: '{{clusterName}}'
        namespace: '{{namespace}}'
      revisionHistoryLimit: 0
      source:
        repoURL: 'https://github.com/yanirw/DevOps-Lab'
        targetRevision: feat/monitoring
        path: infra/monitoring/kube-prometheus-stack
        helm:
          releaseName: monitoring
          valueFiles:
            - ../env/{{environment}}-values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true 