apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tls-external
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: {{ .Values.cloudflareTls.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.cloudflareTls.secretStoreRef.name }}
    kind: {{ .Values.cloudflareTls.secretStoreRef.kind }}
  target:
    name: {{ .Values.cloudflareTls.secretName }}
    creationPolicy: Owner
  data:
  - secretKey: tls.crt
    remoteRef:
      key: {{ .Values.cloudflareTls.secretKeys | first | get "key" }}
      property: {{ .Values.cloudflareTls.secretKeys | first | get "property" }}
  - secretKey: tls.key
    remoteRef:
      key: {{ .Values.cloudflareTls.secretKeys | last | get "key" }}
      property: {{ .Values.cloudflareTls.secretKeys | last | get "property" }}