apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-tls-external
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "externalsecret.annotations" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.cloudflareTls.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.cloudflareTls.secretStoreRef.name }}
    kind: {{ .Values.cloudflareTls.secretStoreRef.kind }}
  target:
    name: {{ .Values.cloudflareTls.secretName }}
    creationPolicy: Owner
  data:
  {{- range .Values.cloudflareTls.secretKeys }}
  - secretKey: {{ .name }}
    remoteRef:
      key: {{ .key }}
      property: {{ .property }}
  {{- end }}