apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.cloudflareTls.secretStoreRef.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "secretstore.annotations" . | nindent 4 }}
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId }}
      auth:
        workloadIdentity:
          serviceAccountRef:
            name: {{ .Values.gcp.serviceAccount.name }}
            namespace: {{ .Values.gcp.serviceAccount.namespace }}