apiVersion: external-secrets.io/v1beta1
kind: {{ .Values.cloudflareTls.secretStoreRef.kind }}
metadata:
  name: {{ .Values.cloudflareTls.secretStoreRef.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.gcp.clusterLocation }}
          clusterName: {{ .Values.gcp.clusterName }}
          serviceAccountRef:
            name: {{ .Values.gcp.serviceAccount.name }}
            namespace: {{ .Values.gcp.serviceAccount.namespace }}