apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.gcp.clusterLocation }}
          clusterName: {{ .Values.gcp.clusterName }}
          serviceAccountRef:
            name: {{ .Values.gcp.serviceAccount.name }}
            namespace: {{ .Values.gcp.serviceAccount.namespace }}