apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gcp.serviceAccount.name }}
  namespace: {{ .Values.gcp.serviceAccount.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-secrets-role
  namespace: {{ .Values.gcp.serviceAccount.namespace }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-secrets-rolebinding
  namespace: {{ .Values.gcp.serviceAccount.namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.gcp.serviceAccount.name }}
  namespace: {{ .Values.gcp.serviceAccount.namespace }}
roleRef:
  kind: Role
  name: external-secrets-role
  apiGroup: rbac.authorization.k8s.io 