apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gcp.serviceAccount.name }}
  namespace: {{ .Values.gcp.serviceAccount.namespace }}
  annotations:
    iam.gke.io/gcp-service-account: gke-external-secrets@yan-lab.iam.gserviceaccount.com