
name: frontend
replicaCount: 3
image:
  repository: ghcr.io/yanirw/frontend
  pullPolicy: IfNotPresent
  tag: "3.1.2"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3000
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: true
  path: "/"
  servicePort: 3000
  