gcp:
  projectId: "yan-lab"
  serviceAccount:
    name: external-secret-sa
    namespace: external-secrets

cloudflareTls:
  secretName: cloudflare-tls
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  secretKeys:
    - name: cert
      key: projects/yan-lab/secrets/cloudflare-tls
      property: cert
    - name: key
      key: projects/yan-lab/secrets/cloudflare-tls
      property: key 