gcp:
  projectId: "yan-lab"
  serviceAccount:
    name: external-secret-sa
    namespace: external-secrets
  clusterName: "yan-lab-gke-cl"
  clusterLocation: "me-west1"  

cloudflareTls:
  secretName: cloudflare-tls
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  secretKeys:
    - name: cert
      key: cloudflare-tls  
      property: cert
    - name: key
      key: cloudflare-tls  
      property: key