gcp:
  projectId: "yan-lab"
  clusterName: "yan-lab-gke-cl"
  clusterLocation: "me-west1"

serviceAccount:
  name: external-secret-sa
  namespace: external-secrets
  gcpServiceAccount: "gke-external-secrets@yan-lab.iam.gserviceaccount.com"

secretStore:
  name: gcp-secret-store

cloudflareTls:
  secretName: cloudflare-tls
  refreshInterval: "1h"
  secretKeys:
    - key: cloudflare-tls
      property: cert
    - key: cloudflare-tls
      property: key