apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  refreshInterval: "15m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    name: grafana-admin-credentials
    template:
      type: Opaque
  data:
    - secretKey: admin-password
      remoteRef:
        key: monitoring_grafana_admin
        property: latest 