apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    kubernetes.io/metadata.name: monitoring
    # Add labels for network policies if needed
    # pod-security.kubernetes.io/enforce: restricted 