apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore  
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: yan-lab
      auth:
        workloadIdentity:
          clusterLocation: me-west1
          clusterName: yan-lab-gke-cl
          serviceAccountRef:
            name: external-secret-sa
            namespace: external-secrets
