name: echo-server
replicaCount: 3
image:
  repository: ghcr.io/yanirw/echo-server
  pullPolicy: IfNotPresent
  tag: "3.0.0"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
  metricsPort: 8080 
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
nodeSelector: {}
tolerations: []
affinity: {}
ingress:
  enabled: true
  path: "/echo"
  servicePort: 5000