apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - clusterName: gcp-cluster
        environment: dev
        namespace: external-secrets
        gitRef: HEAD
  template:
    metadata:
      labels:
        domain: secrets
      name: secrets-{{environment}}
    spec:
      project: default
      destination:
        name: '{{clusterName}}'
        namespace: '{{namespace}}'
      revisionHistoryLimit: 0
      source:
        helm:
          releaseName: secrets
          valueFiles:
          - values.yaml
        path: infra/secrets
        repoURL: 'https://github.com/yanirw/guitarnetes2.0'
        targetRevision: '{{gitRef}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true 
        - ApplyOutOfSyncOnly=true
        - RespectSyncWave=true