apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: umbrella-appset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - clusterName: gcp-cluster
        environment: dev
        namespace: default
        gitRef: HEAD
  template:
    metadata:
      labels:
        domain: myapp-umbrella
      name: myapp-{{environment}}
    spec:
      project: default
      destination:
        name: '{{clusterName}}'
        namespace: '{{namespace}}'
      revisionHistoryLimit: 0
      source:
        helm:
          releaseName: umbrella
          valueFiles:
          - env/values-{{environment}}.yaml
        path: infra/app-charts
        repoURL: 'https://github.com/yanirw/DevOps-Lab'
        targetRevision: '{{gitRef}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true