apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-projects
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: argocd-projects
            environment: dev
  template:
    metadata:
      name: 'argocd-projects-{{environment}}'
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: 'https://github.com/yanirw/DevOps-Lab'
        targetRevision: HEAD
        path: infra/argocd/projects
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true