apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: grafana-frontend-config
  namespace: {{ .Release.Namespace }}
spec:
  redirectToHttps:
    enabled: true
  sslPolicy: "gke-ssl-policy" 