apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: master-appset
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - environment: dev
                  clusterName: gcp-cluster
          - list:
              elements:
                - name: applications
                  path: infra/argocd/applications
                - name: monitoring
                  path: infra/argocd/monitoring
  template:
    metadata:
      name: "app-of-apps-{{environment}}-{{name}}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/yanirw/DevOps-Lab
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
