name: Helm CI

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/app-charts/**'  
  pull_request:
    paths:
      - 'infra/app-charts/**'

jobs:
  helm_check:
    name: Helm Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'

    - name: Lint and Template Helm Charts
      run: |
        cd ./infra/app-charts
        
        for values_file in env/values-*.yaml; do
          env=$(basename $values_file .yaml | sed 's/values-//')
          echo "Processing environment: $env"
          
          echo "Linting chart for $env..."
          helm lint . -f $values_file
          
          echo "Templating chart for $env..."
          helm template test . -f $values_file
        done

        echo "All Helm checks completed"